# GitHub Actions Labeler Configuration for FKS Main Service
# Automatically applies labels to PRs based on changed files

# Documentation changes (README, etc.)
documentation:
  - changed-files:
      - any-glob-to-any-file: 
          - 'README.md'
          - '**/*.md'
          - '.github/**/*.md'

# Rust code (main service)
rust:
  - changed-files:
      - any-glob-to-any-file: 
          - 'src/**/*.rs'
          - 'Cargo.toml'
          - 'Cargo.lock'

# Python code (shared services, tests)
python:
  - changed-files:
      - any-glob-to-any-file: 
          - 'src/**/*.py'
          - 'requirements*.txt'
          - 'pyproject.toml'
          - 'setup.py'
      - all-globs-to-all-files: '!tests/**'

# Core Rust application code
core:
  - changed-files:
      - any-glob-to-any-file: 
          - 'src/main.rs'
          - 'src/config.rs'
          - 'src/routes.rs'
          - 'src/k8s.rs'
          - 'src/monitor.rs'

# Shared Python services
shared:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/shared/**/*.py'
          - 'src/services/**/*.py'

# Authentication (security-sensitive)
auth:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/authentication/**/*.py'
          - 'src/authentication/**/*.rs'

# Monitoring and observability
monitoring:
  - changed-files:
      - any-glob-to-any-file:
          - 'monitoring/**/*'
          - 'src/monitor.rs'
          - 'src/shared/monitor/**/*.py'

# Kubernetes integration
kubernetes:
  - changed-files:
      - any-glob-to-any-file:
          - 'k8s/**/*'
          - 'src/k8s.rs'
          - '*.yaml'
          - '*.yml'

# Test files
tests:
  - changed-files:
      - any-glob-to-any-file: 
          - 'tests/**/*.rs'
          - 'tests/**/*.py'
          - 'pytest.ini'

# Security-sensitive files
security:
  - changed-files:
      - any-glob-to-any-file:
          - 'requirements*.txt'
          - '.env*'
          - 'docker-compose*.yml'
          - 'src/authentication/**/*'
          - '.github/workflows/**'
          - 'Cargo.toml'
          - 'Cargo.lock'

# Docker and infrastructure
docker:
  - changed-files:
      - any-glob-to-any-file:
          - 'Dockerfile*'
          - 'docker-compose*.yml'
          - '.dockerignore'
          - 'entrypoint.sh'

# Configuration files
config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.toml'
          - '*.yaml'
          - '*.yml'
          - '*.ini'
          - '*.cfg'
          - '.github/**/*'
          - 'Makefile'
          - 'ruff.toml'
          - 'mypy.ini'

# Scripts and automation
scripts:
  - changed-files:
      - any-glob-to-any-file:
          - '*.sh'
          - 'scripts/**/*'

# SQL and database
database:
  - changed-files:
      - any-glob-to-any-file:
          - 'sql/**/*'
          - '**/migrations/**/*'

# Dependencies
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'requirements*.txt'
          - 'Cargo.toml'
          - 'Cargo.lock'
          - 'pyproject.toml'
          - 'setup.py'

# WIP (Work in Progress) - for draft PRs
wip:
  - changed-files:
      - any-glob-to-any-file: '**/*WIP*'
  - draft: true

# Breaking changes (requires major review)
breaking:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/main.rs'
          - 'src/config.rs'
          - 'Cargo.toml'
          - 'src/shared/**/*.py'
