name: Docker Build and Push

on:
  push:
    branches: [main, develop]
    tags:
      - "v*"
  pull_request:
    branches: [main]

env:
  SERVICE_NAME: main
  DOCKER_USERNAME: nuniesmith
  DOCKER_REPO: nuniesmith/fks
  SERVICE_PORT: 8010

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Run tests
        run: |
          cargo test --all-features || true

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REPO }}
          tags: |
            type=raw,value=${{ env.SERVICE_NAME }}-latest,enable={{is_default_branch}}
            type=sha,prefix=${{ env.SERVICE_NAME }}-,format=short
            type=ref,event=branch,prefix=${{ env.SERVICE_NAME }}-
            type=semver,pattern={{version}},prefix=${{ env.SERVICE_NAME }}-
            type=semver,pattern={{major}}.{{minor}},prefix=${{ env.SERVICE_NAME }}-
            type=semver,pattern={{major}},prefix=${{ env.SERVICE_NAME }}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.meta.outputs.digest }}

      - name: Deploy to Kubernetes
        if: success()
        run: |
          # Configure SSH
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/jump_key
          chmod 600 ~/.ssh/jump_key

          # Add jump server to known hosts
          ssh-keyscan -H github.fkstrading.xyz >> ~/.ssh/known_hosts 2>/dev/null || true

          # Configuration
          SERVICE_NAME="${{ env.SERVICE_NAME }}"
          IMAGE="${{ env.DOCKER_REPO }}:${{ env.SERVICE_NAME }}-latest"
          NAMESPACE="fks-trading"
          DEPLOYMENT_NAME="fks-$SERVICE_NAME"
          CONTAINER_NAME="fks-$SERVICE_NAME"
          JUMP_SERVER="github.fkstrading.xyz"
          JUMP_USER="github-actions"
          K8S_HOST="${{ secrets.K8S_HOST }}"
          K8S_USER="github-actions"

          echo "🚀 Deploying $SERVICE_NAME to Kubernetes"
          echo "   Image: $IMAGE"
          echo "   Deployment: $DEPLOYMENT_NAME"
          echo "   Namespace: $NAMESPACE"

          # Setup K8s SSH key if provided
          if [ -n "${{ secrets.K8S_SSH_KEY }}" ]; then
            echo "${{ secrets.K8S_SSH_KEY }}" > ~/.ssh/k8s_key
            chmod 600 ~/.ssh/k8s_key
          fi

          # Function to run kubectl command
          run_kubectl() {
            local cmd="$1"
            if [ -n "$K8S_HOST" ]; then
              # Use K8s key if available, otherwise use jump key
              if [ -f ~/.ssh/k8s_key ]; then
                K8S_KEY_FILE=~/.ssh/k8s_key
              else
                K8S_KEY_FILE=~/.ssh/jump_key
              fi
              # SSH into K8s server via jump server
              ssh -i "$K8S_KEY_FILE" -o ProxyJump=$JUMP_USER@$JUMP_SERVER -o StrictHostKeyChecking=no $K8S_USER@$K8S_HOST "$cmd"
            else
              # Run kubectl on jump server
              ssh -i ~/.ssh/jump_key -o StrictHostKeyChecking=no $JUMP_USER@$JUMP_SERVER "$cmd"
            fi
          }

          # Check if deployment exists
          echo "📋 Checking if deployment exists..."
          if run_kubectl "kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE" > /dev/null 2>&1; then
            echo "✅ Deployment $DEPLOYMENT_NAME exists"
            
            # Get current image
            CURRENT_IMAGE=$(run_kubectl "kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath='{.spec.template.spec.containers[0].image}'" 2>/dev/null || echo "")
            if [ -n "$CURRENT_IMAGE" ]; then
              echo "   Current image: $CURRENT_IMAGE"
            fi
            echo "   New image: $IMAGE"
            
            # Update deployment
            echo "🔄 Updating deployment..."
            if run_kubectl "kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$IMAGE -n $NAMESPACE"; then
              echo "✅ Image updated"
            else
              echo "⚠️  Failed to update image, trying alternative method..."
              PATCH_JSON="{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"$CONTAINER_NAME\",\"image\":\"$IMAGE\"}]}}}}"
              if run_kubectl "kubectl patch deployment $DEPLOYMENT_NAME -n $NAMESPACE -p '$PATCH_JSON'"; then
                echo "✅ Image updated via patch"
              else
                echo "❌ Failed to update deployment"
                exit 1
              fi
            fi
            
            # Restart deployment
            echo "🔄 Restarting deployment..."
            run_kubectl "kubectl rollout restart deployment/$DEPLOYMENT_NAME -n $NAMESPACE" || echo "⚠️  Failed to restart deployment"
            
            # Wait for rollout
            echo "⏳ Waiting for rollout to complete..."
            run_kubectl "kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE --timeout=300s" || echo "⚠️  Rollout timeout"
            
            # Show status
            echo ""
            echo "📊 Deployment status:"
            run_kubectl "kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE"
            echo ""
            echo "📊 Pod status:"
            run_kubectl "kubectl get pods -n $NAMESPACE -l app=$SERVICE_NAME" || \
            run_kubectl "kubectl get pods -n $NAMESPACE | grep $SERVICE_NAME" || \
            echo "   (No pods found)"
          else
            echo "❌ Deployment $DEPLOYMENT_NAME not found in namespace $NAMESPACE"
            echo "Available deployments:"
            run_kubectl "kubectl get deployments -n $NAMESPACE" || true
            exit 1
          fi

          echo "✅ Deployment complete!"
