name: Codebase Cleanup and Health Check

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  cleanup-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Run analysis script
        run: |
          python scripts/analyze_src_structure.py
      
      - name: Check for empty files
        id: check-empty
        run: |
          EMPTY_COUNT=$(find . -type f -size 0 \
            -not -path "./.git/*" \
            -not -path "./.pytest_cache/*" \
            -not -path "./__pycache__/*" \
            -not -path "./node_modules/*" \
            -not -path "./.venv/*" \
            -not -path "./venv/*" | wc -l)
          
          echo "empty_files=$EMPTY_COUNT" >> $GITHUB_OUTPUT
          
          if [ $EMPTY_COUNT -gt 0 ]; then
            echo "⚠️ Found $EMPTY_COUNT empty files"
            find . -type f -size 0 \
              -not -path "./.git/*" \
              -not -path "./.pytest_cache/*" \
              -not -path "./__pycache__/*" \
              -not -path "./node_modules/*" \
              -not -path "./.venv/*" \
              -not -path "./venv/*"
          else
            echo "✅ No empty files found"
          fi
      
      - name: Check for small stub files
        id: check-small
        run: |
          SMALL_COUNT=$(find . -type f -size -100c -name "*.py" \
            -not -path "./.git/*" \
            -not -path "./.pytest_cache/*" \
            -not -path "./__pycache__/*" \
            -not -path "./node_modules/*" \
            -not -path "./.venv/*" \
            -not -path "./venv/*" | wc -l)
          
          echo "small_files=$SMALL_COUNT" >> $GITHUB_OUTPUT
          
          if [ $SMALL_COUNT -gt 50 ]; then
            echo "⚠️ Found $SMALL_COUNT small Python files (<100 bytes)"
          else
            echo "✅ Small file count is acceptable: $SMALL_COUNT"
          fi
      
      - name: Generate cleanup report
        if: steps.check-empty.outputs.empty_files > 0 || steps.check-small.outputs.small_files > 50
        run: |
          cat << EOF > cleanup-report.md
          # Cleanup Report - $(date +%Y-%m-%d)
          
          ## Summary
          - Empty files found: ${{ steps.check-empty.outputs.empty_files }}
          - Small Python files: ${{ steps.check-small.outputs.small_files }}
          
          ## Action Required
          Review and clean up the identified files using:
          \`\`\`bash
          python scripts/cleanup_files.py
          \`\`\`
          
          ## Analysis Report
          See \`docs/SRC_STRUCTURE_ANALYSIS.json\` for detailed analysis.
          EOF
          
          cat cleanup-report.md
      
      - name: Upload analysis report
        uses: actions/upload-artifact@v3
        with:
          name: cleanup-analysis
          path: |
            docs/SRC_STRUCTURE_ANALYSIS.json
            cleanup-report.md
          retention-days: 30
      
      - name: Create issue if cleanup needed
        if: steps.check-empty.outputs.empty_files > 5
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('cleanup-report.md', 'utf8');
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🧹 Codebase Cleanup Required',
              body: report,
              labels: ['maintenance', 'automated']
            });
